import type { IExercise } from '@/types';

const defaultExercises: Omit<IExercise, '_id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Machine Chest Press',
    category: 'upper-body',
    description: 'Targets chest, shoulders, and triceps using a chest press machine.',
    setupCues: ['Adjust seat height so handles are at mid-chest level', 'Sit with back flat against the pad', 'Grip the handles firmly at shoulder width'],
    executionCues: ['Press forward with controlled movement', 'Extend arms fully without locking elbows', 'Return to starting position slowly'],
    breathingCues: ['Exhale during the press', 'Inhale when returning to start'],
    commonMistakes: ['Arching the back excessively', 'Using momentum instead of controlled movement', 'Locking elbows at the top'],
    safetyNotes: ['Do not train to failure in the first month', 'Stop if you feel pain in shoulders or wrists', 'Choose a weight with 2-3 reps in reserve'],
    referenceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/ChestPress'],
    isShared: true,
  },
  {
    name: 'Lat Pulldown',
    category: 'upper-body',
    description: 'Pulls the bar toward your upper chest to target the back.',
    setupCues: ['Adjust thigh pad to keep body stable', 'Grip the bar slightly wider than shoulder width'],
    executionCues: ['Pull the bar toward your upper chest', 'Squeeze shoulder blades together at the bottom', 'Return slowly without swinging your body'],
    breathingCues: ['Exhale when pulling down', 'Inhale when returning up'],
    commonMistakes: ['Swinging the body to pull the weight', 'Pulling the bar behind the neck', 'Using too much weight and losing control'],
    safetyNotes: ['Keep chest up and core engaged', 'Stop if you feel shoulder strain', 'Use weight you can pull 8-12 times with control'],
    referenceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/LatPulldown'],
    isShared: true,
  },
  {
    name: 'Leg Press',
    category: 'lower-body',
    description: 'A machine-based squat alternative targeting the legs.',
    setupCues: ['Adjust seat so knees are bent at 90 degrees at the bottom', 'Place entire foot on the platform', 'Keep knees tracking over toes'],
    executionCues: ['Press the platform away by extending your legs', 'Do not lock your knees aggressively at the top', 'Lower the platform slowly back to the starting position'],
    breathingCues: ['Exhale when pressing away', 'Inhale when lowering'],
    commonMistakes: ['Lifting heels off the platform', 'Locking knees at the top', 'Lowering the weight too deeply if it causes lower back rounding'],
    safetyNotes: ['Do not lock knees forcefully', 'Start with light weight to learn the machine', 'Ask a trainer to check your setup'],
    referenceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LVLegPress'],
    isShared: true,
  },
  {
    name: 'Seated Cable Row',
    category: 'upper-body',
    description: 'Targets the upper back and biceps.',
    setupCues: ['Sit upright with chest tall', 'Keep a slight bend in your knees'],
    executionCues: ['Pull the handle toward your abdomen', 'Squeeze your shoulder blades together', 'Extend arms fully on the return'],
    breathingCues: ['Exhale when pulling', 'Inhale when extending'],
    commonMistakes: ['Rounding the back during the pull', 'Jerking the weight with momentum', 'Shrugging shoulders up'],
    safetyNotes: ['Maintain a neutral spine throughout', 'Keep weight light enough to hold form'],
    referenceUrls: ['https://exrx.net/WeightExercises/BackGeneral/CableSeatedRow'],
    isShared: true,
  },
  {
    name: 'Machine Shoulder Press',
    category: 'upper-body',
    description: 'Overhead pressing movement on a machine.',
    setupCues: ['Adjust seat so handles are at shoulder height', 'Sit with back against the pad', 'Grip handles firmly'],
    executionCues: ['Press upward until arms are nearly straight', 'Lower with control to shoulder height'],
    breathingCues: ['Exhale on the press', 'Inhale on the descent'],
    commonMistakes: ['Over-arching the lower back', 'Using excessive momentum', 'Flaring elbows too far out'],
    safetyNotes: ['Use controlled movement', 'Stop if you feel pain in the shoulders'],
    referenceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/ShoulderPress'],
    isShared: true,
  },
  {
    name: 'Leg Curl',
    category: 'lower-body',
    description: 'Targets the hamstrings.',
    setupCues: ['Adjust pad so it sits just above your heels', 'Keep hips flat against the bench'],
    executionCues: ['Curl your heels toward your glutes', 'Squeeze hamstrings at the top', 'Lower slowly to the starting position'],
    breathingCues: ['Exhale on the curl', 'Inhale on the descent'],
    commonMistakes: ['Lifting hips off the bench', 'Using momentum', 'Not controlling the lowering phase'],
    safetyNotes: ['Keep movement slow and controlled', 'Start with light weight in the first month'],
    referenceUrls: ['https://exrx.net/WeightExercises/Hamstrings/LVLyingLegCurl'],
    isShared: true,
  },
  {
    name: 'Leg Extension',
    category: 'lower-body',
    description: 'Isolates the quadriceps.',
    setupCues: ['Adjust back pad so knees align with the machine pivot', 'Shin pad should sit near the top of your ankle'],
    executionCues: ['Extend your legs until they are nearly straight', 'Lower slowly without letting the weight slam'],
    breathingCues: ['Exhale on the extension', 'Inhale on the lowering'],
    commonMistakes: ['Locking knees at the top', 'Using too much weight', 'Partial range of motion'],
    safetyNotes: ['Do not lock knees aggressively', 'Control both directions of the movement'],
    referenceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LVLegExtension'],
    isShared: true,
  },
  {
    name: 'Biceps Curl Machine',
    category: 'upper-body',
    description: 'Isolated biceps curl on a machine.',
    setupCues: ['Adjust seat so elbows align with the machine pivot', 'Grip handles with palms facing up'],
    executionCues: ['Curl upward until forearms are near vertical', 'Lower slowly to the starting position'],
    breathingCues: ['Exhale on the curl', 'Inhale on the descent'],
    commonMistakes: ['Swinging elbows forward', 'Using momentum', 'Incomplete range of motion'],
    safetyNotes: ['Keep elbows at your sides', 'Use lighter weight if form breaks down'],
    referenceUrls: ['https://exrx.net/WeightExercises/Biceps/Curl'],
    isShared: true,
  },
  {
    name: 'Triceps Pushdown',
    category: 'upper-body',
    description: 'Cable-based triceps exercise.',
    setupCues: ['Stand upright with elbows tucked at your sides', 'Grip the bar or rope firmly'],
    executionCues: ['Push the bar down until your arms are nearly straight', 'Return slowly to the starting position'],
    breathingCues: ['Exhale on the push', 'Inhale on the return'],
    commonMistakes: ['Swinging elbows away from the body', 'Using too much weight', 'Incomplete range of motion'],
    safetyNotes: ['Keep elbows stationary', 'Start with manageable weight'],
    referenceUrls: ['https://exrx.net/WeightExercises/Triceps/Pushdown'],
    isShared: true,
  },
  {
    name: 'Calf Raise',
    category: 'lower-body',
    description: 'Builds calf strength using a standing or seated machine.',
    setupCues: ['Place balls of feet on the platform with heels hanging off', 'Stand tall with shoulders back'],
    executionCues: ['Raise your heels as high as possible', 'Pause briefly at the top', 'Lower slowly until a mild stretch is felt'],
    breathingCues: ['Exhale when rising', 'Inhale when lowering'],
    commonMistakes: ['Bouncing at the bottom', 'Not reaching full extension', 'Using momentum'],
    safetyNotes: ['Keep movement controlled', 'Start with moderate weight'],
    referenceUrls: ['https://exrx.net/WeightExercises/Gastrocnemius/CalfRaise'],
    isShared: true,
  },
  {
    name: 'Abdominal Crunch',
    category: 'core',
    description: 'Machine or floor-based core exercise.',
    setupCues: ['Adjust pad so it sits at mid-chest', 'Grip handles lightly for stability'],
    executionCues: ['Crunch forward and curl your torso', 'Hold briefly at the top', 'Return slowly without resting at the bottom'],
    breathingCues: ['Exhale on the crunch', 'Inhale when returning'],
    commonMistakes: ['Pulling with arms instead of abs', 'Going too fast', 'Rounding the lower back'],
    safetyNotes: ['Feel contraction in the abs, not the neck', 'Use light resistance initially'],
    referenceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/Crunch'],
    isShared: true,
  },
  {
    name: 'Hip Abduction',
    category: 'lower-body',
    description: 'Strengthens outer hips and glutes.',
    setupCues: ['Sit upright with pads resting on the outside of your thighs'],
    executionCues: ['Push legs apart against resistance', 'Squeeze glutes at the top', 'Return slowly to the starting position'],
    breathingCues: ['Exhale when pushing apart', 'Inhale when returning'],
    commonMistakes: ['Leaning forward excessively', 'Using too much weight', 'Jerky movement'],
    safetyNotes: ['Use controlled movement', 'Start with comfortable resistance'],
    referenceUrls: ['https://exrx.net/WeightExercises/HipAbductors/HipAbduction'],
    isShared: true,
  },
  {
    name: 'Hip Adduction',
    category: 'lower-body',
    description: 'Strengthens inner thighs.',
    setupCues: ['Sit upright with pads resting on the inside of your thighs'],
    executionCues: ['Squeeze legs together against resistance', 'Hold briefly at the top', 'Return slowly to the starting position'],
    breathingCues: ['Exhale when squeezing', 'Inhale when returning'],
    commonMistakes: ['Arching the back', 'Using excessive momentum', 'Incomplete range of motion'],
    safetyNotes: ['Maintain upright posture', 'Start with light resistance'],
    referenceUrls: ['https://exrx.net/WeightExercises/HipAdductors/HipAdduction'],
    isShared: true,
  },
  {
    name: 'Lat Pulldown (Reverse Grip)',
    category: 'upper-body',
    description: 'Reverse-grip variation emphasizing lower lats.',
    setupCues: ['Sit with thighs secure under the pad', 'Grip the bar with palms facing you at shoulder width'],
    executionCues: ['Pull the bar down to your chest', 'Squeeze your back at the bottom', 'Return slowly'],
    breathingCues: ['Exhale when pulling down', 'Inhale when returning'],
    commonMistakes: ['Leaning back excessively', 'Using momentum', 'Incomplete range of motion'],
    safetyNotes: ['Maintain controlled movement', 'Choose a manageable weight'],
    referenceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/LatPulldownCloseGrip'],
    isShared: true,
  },
  {
    name: 'Seated Row',
    category: 'upper-body',
    description: 'Horizontal rowing targeting middle back.',
    setupCues: ['Sit upright with chest tall', 'Keep knees slightly bent'],
    executionCues: ['Pull handle toward your midsection', 'Squeeze shoulder blades together', 'Return to full arm extension'],
    breathingCues: ['Exhale when pulling', 'Inhale when extending'],
    commonMistakes: ['Rounding the back', 'Using momentum', 'Shrugging shoulders'],
    safetyNotes: ['Maintain neutral spine', 'Control both phases'],
    referenceUrls: ['https://exrx.net/WeightExercises/BackGeneral/CableSeatedRow'],
    isShared: true,
  },
  {
    name: 'Pec Deck / Chest Fly',
    category: 'upper-body',
    description: 'Isolates the chest with a controlled fly motion.',
    setupCues: ['Adjust seat so handles are at chest level', 'Sit with back flat against the pad'],
    executionCues: ['Bring handles together in front of your chest', 'Squeeze your chest at the peak', 'Return slowly with control'],
    breathingCues: ['Exhale when bringing handles together', 'Inhale when returning'],
    commonMistakes: ['Overextending the arms', 'Using momentum', 'Not feeling chest contraction'],
    safetyNotes: ['Use lighter weight for this exercise', 'Focus on muscle contraction, not weight moved'],
    referenceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/Fly'],
    isShared: true,
  },
  {
    name: 'Lateral Raise',
    category: 'upper-body',
    description: 'Builds side deltoids.',
    setupCues: ['Stand with feet shoulder-width apart', 'Hold dumbbells or machine handles at your sides'],
    executionCues: ['Raise arms out to the sides until elbows are shoulder height', 'Lower slowly to the starting position'],
    breathingCues: ['Exhale when raising', 'Inhale when lowering'],
    commonMistakes: ['Swinging the body', 'Lifting too heavy', 'Raising arms above shoulder level'],
    safetyNotes: ['This is a light-weight, high-control exercise', 'Do not use momentum'],
    referenceUrls: ['https://exrx.net/WeightExercises/DeltoidLateral/LateralRaise'],
    isShared: true,
  },
  {
    name: 'Back Extension',
    category: 'lower-body',
    description: 'Strengthens the lower back and core.',
    setupCues: ['Position hips at the top of the pad', 'Cross your arms in front of your chest or place hands behind your head'],
    executionCues: ['Lower your torso until you feel a stretch in your hamstrings', 'Raise your torso back to neutral without over-arching'],
    breathingCues: ['Exhale when raising', 'Inhale when lowering'],
    commonMistakes: ['Over-arching at the top', 'Using momentum', 'Locking knees'],
    safetyNotes: ['Only perform if comfortable with the setup', 'Stop immediately if you feel back pain', 'Start with bodyweight only'],
    referenceUrls: ['https://exrx.net/WeightExercises/ErectorSpinae/BackExtension'],
    isShared: true,
  },
  {
    name: 'Machine Lateral Raise',
    category: 'upper-body',
    description: 'Side shoulder isolation using a machine.',
    setupCues: ['Sit with back against the pad', 'Position arms on the pads'],
    executionCues: ['Raise the pads outward to shoulder height', 'Lower slowly back to the start'],
    breathingCues: ['Exhale when raising', 'Inhale when lowering'],
    commonMistakes: ['Lifting too fast', 'Using excessive weight', 'Partial range of motion'],
    safetyNotes: ['Use a weight where you can maintain strict form', 'This is a controlled, high-rep exercise'],
    referenceUrls: ['https://exrx.net/WeightExercises/DeltoidLateral/LateralRaise'],
    isShared: true,
  },
  {
    name: 'Hack Squat',
    category: 'lower-body',
    description: 'Machine-based squat with back support.',
    setupCues: ['Shoulders against the pads', 'Feet on the platform at shoulder width', 'Release safety catches'],
    executionCues: ['Lower your body until thighs are parallel to the platform', 'Press back up without locking knees'],
    breathingCues: ['Inhale when lowering', 'Exhale when pressing up'],
    commonMistakes: ['Knees caving inward', 'Lifting heels', 'Partial range of motion'],
    safetyNotes: ['Learn the machine setup from a trainer before using heavy weight', 'Keep weight manageable in the first month'],
    referenceUrls: ['https://exrx.net/WeightExercises/Quadriceps/HackSquat'],
    isShared: true,
  },
  {
    name: 'Incline Chest Press',
    category: 'upper-body',
    description: 'Upper chest emphasis using an incline machine.',
    setupCues: ['Set the incline bench to 30-45 degrees', 'Handles should align with upper chest'],
    executionCues: ['Press upward with control', 'Extend arms without locking elbows', 'Lower slowly to chest level'],
    breathingCues: ['Exhale on the press', 'Inhale when lowering'],
    commonMistakes: ['Flaring elbows too wide', 'Using momentum', 'Partial range of motion'],
    safetyNotes: ['Maintain controlled movement', 'Choose a weight with 2-3 reps in reserve'],
    referenceUrls: ['https://exrx.net/WeightExercises/PectoralClavicular/InclinePress'],
    isShared: true,
  },
  {
    name: 'Assisted Pull-up',
    category: 'upper-body',
    description: 'Pull-ups with counterweight assistance for beginners.',
    setupCues: ['Set the assistance weight appropriately', 'Grip the bar slightly wider than shoulder width', 'Kneel or stand on the assistance platform'],
    executionCues: ['Pull your chin above the bar', 'Lower slowly to full arm extension', 'Keep core engaged throughout'],
    breathingCues: ['Exhale when pulling up', 'Inhale when lowering'],
    commonMistakes: ['Swinging the body', 'Not reaching full extension', 'Using too little assistance'],
    safetyNotes: ['Keep movement controlled', 'Adjust assistance so you can perform 8-12 reps'],
    referenceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/AssistedPullup'],
    isShared: true,
  },
  {
    name: 'Reverse Pec Deck',
    category: 'upper-body',
    description: 'Rear deltoid and upper back fly.',
    setupCues: ['Sit facing the machine', 'Grip handles with palms facing each other'],
    executionCues: ['Pull handles back, squeezing your shoulder blades', 'Return slowly to the starting position'],
    breathingCues: ['Exhale when pulling back', 'Inhale when returning'],
    commonMistakes: ['Using too much weight', 'Jerking the movement', 'Not squeezing shoulder blades'],
    safetyNotes: ['Use light weight', 'Focus on rear deltoid contraction'],
    referenceUrls: ['https://exrx.net/WeightExercises/BackGeneral/ReverseFly'],
    isShared: true,
  },
  {
    name: 'Triceps Extension',
    category: 'upper-body',
    description: 'Overhead cable or machine triceps extension.',
    setupCues: ['Face away from the machine', 'Grip the rope or bar overhead with elbows near your ears'],
    executionCues: ['Extend your arms upward', 'Lower slowly behind your head'],
    breathingCues: ['Exhale when extending', 'Inhale when lowering'],
    commonMistakes: ['Flaring elbows outward', 'Using momentum', 'Incomplete range of motion'],
    safetyNotes: ['Keep elbows close to your head', 'Start with lighter weight'],
    referenceUrls: ['https://exrx.net/WeightExercises/Triceps/CableOverheadExtension'],
    isShared: true,
  },
];

export default defaultExercises;
