import type { IExercise } from '@/types';

const defaultExercises: Omit<IExercise, '_id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Machine Chest Press',
    category: 'upper-body',
    description: 'A compound pressing movement that targets the pectoralis major, anterior deltoids, and triceps using a guided machine path. Ideal for beginners learning pressing mechanics before moving to free weights.',
    setupCues: ['Adjust the seat so the handles align with mid-chest level', 'Sit with your back flat against the pad and feet planted firmly', 'Grip the handles at shoulder width with palms facing forward or inward'],
    executionCues: ['Press the handles forward in a smooth, controlled arc', 'Extend your arms fully without forcefully locking the elbows', 'Return to the starting position over 2-3 seconds', 'Keep your shoulder blades retracted throughout the movement'],
    breathingCues: ['Exhale steadily as you press forward', 'Inhale as you return to the starting position'],
    commonMistakes: ['Arching the lower back excessively to push more weight', 'Using momentum by bouncing at the bottom', 'Locking the elbows aggressively at full extension', 'Allowing the elbows to drop below chest level'],
    safetyNotes: ['Keep 2-3 reps in reserve during your first month of training', 'Stop immediately if you feel sharp pain in the shoulders or wrists', 'Use a full range of motion rather than chasing heavy weight'],
    referenceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/LVChestPress'],
    isShared: true,
  },
  {
    name: 'Incline Dumbbell Press',
    category: 'upper-body',
    description: 'An upper-chest emphasizing press performed on an incline bench with dumbbells. Develops the clavicular head of the pectoralis major and anterior deltoids while challenging stabilization.',
    setupCues: ['Set the incline bench to 30-45 degrees', 'Sit back with feet flat on the floor', 'Start with dumbbells at shoulder level, palms facing forward', 'Keep your shoulder blades pinched together and chest up'],
    executionCues: ['Press the dumbbells upward in an arc until they nearly meet', 'Keep the movement controlled on both the press and descent', 'Lower the dumbbells to shoulder level over 2-3 seconds', 'Maintain a slight bend in the elbows at the top'],
    breathingCues: ['Exhale as you press the dumbbells up', 'Inhale as you lower them back down'],
    commonMistakes: ['Setting the incline too steep (above 45 degrees shifts focus to shoulders)', 'Bouncing the dumbbells at the bottom', 'Flaring the elbows too far outward', 'Not controlling the downward phase'],
    safetyNotes: ['Use a spotter when lifting heavy dumbbells', 'Start with lighter weight than your flat press', 'Keep your wrists neutral, not bent backward'],
    referenceUrls: ['https://exrx.net/WeightExercises/PectoralClavicular/IDBInclinePress'],
    isShared: true,
  },
  {
    name: 'Flat Dumbbell Press',
    category: 'upper-body',
    description: 'A free-weight chest press that builds the pectoralis major, anterior deltoids, and triceps. Dumbbells allow a greater range of motion than a barbell and challenge each side independently.',
    setupCues: ['Lie flat on a bench with feet planted on the floor', 'Hold dumbbells at shoulder level with palms facing forward', 'Retract your shoulder blades and keep your chest up', 'Maintain a natural arch in your lower back'],
    executionCues: ['Press the dumbbells upward in a slight arc until arms are nearly straight', 'Lower under control to chest level', 'Keep elbows at roughly 45-60 degrees from the torso', 'Avoid letting the dumbbells drift apart or collide'],
    breathingCues: ['Exhale during the upward press', 'Inhale during the downward phase'],
    commonMistakes: ['Bouncing at the bottom to generate momentum', 'Letting the elbows flare to 90 degrees (strains shoulders)', 'Arching the back excessively', 'Not using a full range of motion'],
    safetyNotes: ['Use a spotter for heavy sets', 'Keep wrists stacked directly over elbows', 'Lower dumbbells no deeper than mid-chest level'],
    referenceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/IDBChestPress'],
    isShared: true,
  },
  {
    name: 'Lat Pulldown',
    category: 'upper-body',
    description: 'A vertical pulling exercise that targets the latissimus dorsi, biceps, and upper back. An excellent alternative for beginners who cannot yet do full pull-ups.',
    setupCues: ['Adjust the thigh pad so it firmly holds your legs in place', 'Grip the bar wider than shoulder width with palms facing away', 'Sit tall with your chest up and core engaged'],
    executionCues: ['Pull the bar down toward your upper chest, not behind your neck', 'Drive your elbows down and back, squeezing your shoulder blades', 'Return to full arm extension slowly over 2-3 seconds', 'Avoid leaning back more than a slight torso angle'],
    breathingCues: ['Exhale as you pull the bar down', 'Inhale as you let it rise back up'],
    commonMistakes: ['Swinging the body to help pull the weight', 'Pulling the bar behind the neck (strains the rotator cuff)', 'Shrugging the shoulders during the pull', 'Using momentum instead of controlled lat activation'],
    safetyNotes: ['Keep your chest up throughout the movement', 'Use a weight that lets you perform 8-12 reps with strict form', 'Stop if you feel pain in the front of the shoulder'],
    referenceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/LatPulldown'],
    isShared: true,
  },
  {
    name: 'Assisted Pull-up',
    category: 'upper-body',
    description: 'A vertical pull-up with counterweight assistance, ideal for building toward unassisted pull-ups. Targets the lats, biceps, and upper back.',
    setupCues: ['Select an appropriate assistance weight on the machine', 'Grip the bar slightly wider than shoulder width, palms facing away', 'Place your knees or feet on the assistance platform'],
    executionCues: ['Pull your chin above the bar', 'Lower slowly to a full dead hang', 'Keep your core engaged and avoid swinging', 'Focus on pulling with your lats, not just your arms'],
    breathingCues: ['Exhale as you pull up', 'Inhale as you lower down'],
    commonMistakes: ['Using too little assistance and straining', 'Swinging the body to gain height', 'Not reaching full arm extension at the bottom', 'Kipping or jerking the movement'],
    safetyNotes: ['Adjust the assistance so you can perform 8-12 clean reps', 'Keep the movement controlled in both directions', 'Avoid shrugging the shoulders'],
    referenceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/AsstPullup'],
    isShared: true,
  },
  {
    name: 'Seated Cable Row',
    category: 'upper-body',
    description: 'A horizontal pulling exercise that develops the middle back, rhomboids, rear deltoids, and biceps. Cable resistance provides consistent tension throughout the range of motion.',
    setupCues: ['Sit upright with your chest tall and shoulders back', 'Keep a slight bend in your knees', 'Grip the handle with both hands', 'Brace your core before each rep'],
    executionCues: ['Pull the handle toward your lower ribcage', 'Squeeze your shoulder blades together at full contraction', 'Return to full arm extension without rounding your back', 'Keep your torso stable — do not rock back and forth'],
    breathingCues: ['Exhale as you pull the handle in', 'Inhale as you extend back to the starting position'],
    commonMistakes: ['Rounding the back during the pull', 'Using momentum by rocking the torso', 'Shrugging the shoulders up toward the ears', 'Not achieving full arm extension on the return'],
    safetyNotes: ['Maintain a neutral spine throughout', 'Keep the weight moderate enough to hold form', 'Avoid jerking the cable at the start of each rep'],
    referenceUrls: ['https://exrx.net/WeightExercises/BackGeneral/CBSeatedRow'],
    isShared: true,
  },
  {
    name: 'Barbell Row',
    category: 'upper-body',
    description: 'A compound free-weight row that builds the entire back — lats, rhomboids, traps, and rear deltoids — while also engaging the core and lower back for stabilization.',
    setupCues: ['Stand with feet shoulder-width apart', 'Hinge forward at the hips keeping your back flat', 'Grip the barbell with hands slightly wider than shoulder width', 'Let the bar hang at arm\'s length below your chest'],
    executionCues: ['Pull the bar toward your lower ribcage', 'Keep your elbows tucked close to your body', 'Squeeze your shoulder blades at the top', 'Lower the bar under control to full arm extension'],
    breathingCues: ['Exhale as you pull the bar up', 'Inhale as you lower it back down'],
    commonMistakes: ['Rounding the lower back (injury risk)', 'Standing too upright and turning it into a shrug', 'Using leg drive instead of back muscles', 'Bouncing the bar at the bottom'],
    safetyNotes: ['Keep your back flat — never rounded', 'Start with light weight to master the hip hinge position', 'Use lifting straps if grip is the limiting factor'],
    referenceUrls: ['https://exrx.net/WeightExercises/BackGeneral/BentOverRow'],
    isShared: true,
  },
  {
    name: 'Machine Shoulder Press',
    category: 'upper-body',
    description: 'An overhead pressing movement on a machine that targets the anterior and medial deltoids, upper chest, and triceps. The guided path makes it safe for beginners.',
    setupCues: ['Adjust the seat so the handles are at shoulder height', 'Sit with your back flat against the pad', 'Grip the handles firmly at shoulder width', 'Keep your feet planted and core braced'],
    executionCues: ['Press upward until your arms are nearly straight', 'Lower with control back to shoulder level', 'Maintain a neutral wrist position throughout', 'Avoid shrugging your shoulders as you press'],
    breathingCues: ['Exhale on the upward press', 'Inhale on the controlled descent'],
    commonMistakes: ['Over-arching the lower back to push more weight', 'Using leg drive to initiate the press', 'Flaring the elbows too far to the sides', 'Pressing the handles behind the head'],
    safetyNotes: ['Use a controlled tempo — no bouncing', 'Stop if you feel pain in the shoulder joint', 'Keep 2-3 reps in reserve in your first month'],
    referenceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/LVShoulderPress'],
    isShared: true,
  },
  {
    name: 'Dumbbell Shoulder Press',
    category: 'upper-body',
    description: 'A free-weight overhead press that builds the anterior and medial deltoids and triceps. Dumbbells challenge each shoulder independently and reveal strength imbalances.',
    setupCues: ['Sit on a bench with back support (or stand with feet shoulder-width)', 'Hold dumbbells at shoulder level with palms facing forward', 'Brace your core and keep your chest up', 'Retract your shoulder blades slightly'],
    executionCues: ['Press the dumbbells overhead in an arc until arms are nearly straight', 'Lower under control to shoulder level', 'Keep elbows at roughly 45 degrees from the torso', 'Avoid leaning back as you press'],
    breathingCues: ['Exhale as you press up', 'Inhale as you lower the dumbbells'],
    commonMistakes: ['Leaning back excessively (shifts load to upper chest)', 'Not controlling the descent', 'Letting the dumbbells drift inward', 'Pressing through one arm faster than the other'],
    safetyNotes: ['Use a spotter for heavier sets', 'Avoid locking the elbows at the top', 'If standing, keep the core braced to protect the lower back'],
    referenceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/DBShoulderPress'],
    isShared: true,
  },
  {
    name: 'Dumbbell Lateral Raise',
    category: 'upper-body',
    description: 'An isolation exercise that targets the medial (side) head of the deltoid. Light weight and strict form are essential — this is not a heavy lifting exercise.',
    setupCues: ['Stand with feet shoulder-width apart', 'Hold dumbbells at your sides with palms facing inward', 'Keep a slight bend in the elbows', 'Maintain a tall posture with shoulders pulled back'],
    executionCues: ['Raise the dumbbells outward to shoulder height (no higher)', 'Lead with the elbows, not the hands', 'Lower slowly over 2-3 seconds', 'Keep the movement smooth and continuous'],
    breathingCues: ['Exhale as you raise the dumbbells', 'Inhale as you lower them'],
    commonMistakes: ['Swinging the body to lift heavier weight', 'Raising the arms above shoulder height (impinges the joint)', 'Using momentum from the hips', 'Shrugging the traps during the raise'],
    safetyNotes: ['This is a light-weight, high-control exercise', 'Never swing or use momentum', 'If you can do 12-15 reps with strict form, the weight is right'],
    referenceUrls: ['https://exrx.net/WeightExercises/DeltoidLateral/DBLateralRaise'],
    isShared: true,
  },
  {
    name: 'Face Pull',
    category: 'upper-body',
    description: 'A cable exercise targeting the rear deltoids, rhomboids, and external rotators. Excellent for posture correction and shoulder health, especially for those who press frequently.',
    setupCues: ['Set the cable pulley to face height', 'Attach a rope handle', 'Grip the rope with both hands, palms facing each other', 'Step back so there is tension on the cable'],
    executionCues: ['Pull the rope toward your face, separating the rope ends', 'Squeeze your rear delts and upper back at full contraction', 'Keep your elbows high throughout', 'Return slowly to the starting position'],
    breathingCues: ['Exhale as you pull toward your face', 'Inhale as the cable returns'],
    commonMistakes: ['Using too much weight and losing form', 'Letting the elbows drop', 'Not separating the rope at the end', 'Rounding the shoulders forward'],
    safetyNotes: ['Use lighter weight than you think you need', 'Focus on the rear deltoid and rotator cuff contraction', 'This is a prehab and aesthetic exercise, not a max lift'],
    referenceUrls: ['https://exrx.net/WeightExercises/DeltoidPosterior/CBFacePull'],
    isShared: true,
  },
  {
    name: 'Pec Deck / Chest Fly',
    category: 'upper-body',
    description: 'An isolation exercise that targets the pectoralis major through a fly movement pattern. The machine provides a controlled arc path with consistent tension.',
    setupCues: ['Adjust the seat so the pads align with chest level', 'Sit with your back flat against the pad', 'Place your forearms against the pads or grip the handles', 'Keep your elbows at roughly shoulder height'],
    executionCues: ['Bring the pads or handles together in front of your chest', 'Squeeze your chest at the peak contraction', 'Return slowly with control to the starting stretch', 'Maintain a slight bend in the elbows throughout'],
    breathingCues: ['Exhale as you bring the pads together', 'Inhale as you open back up'],
    commonMistakes: ['Overextending the arms at the start (shoulder strain)', 'Using heavy weight that turns it into a press', 'Not feeling a chest contraction', 'Hyperextending the shoulders on the return'],
    safetyNotes: ['Use lighter weight than your pressing exercises', 'Focus on the stretch and contraction, not load moved', 'Stop if you feel discomfort in the front of the shoulder'],
    referenceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/LVFly'],
    isShared: true,
  },
  {
    name: 'Dumbbell Biceps Curl',
    category: 'upper-body',
    description: 'An isolation exercise for the biceps brachii. Dumbbells allow supination of the wrist for a full biceps contraction and work each arm independently.',
    setupCues: ['Stand with feet shoulder-width apart', 'Hold dumbbells at your sides with palms facing inward', 'Keep your elbows pinned to your sides', 'Stand tall with shoulders back'],
    executionCues: ['Curl one or both dumbbells upward while rotating the palm to face up', 'Squeeze the biceps at the top', 'Lower slowly over 2-3 seconds', 'Keep the elbow stationary — do not swing it forward'],
    breathingCues: ['Exhale as you curl up', 'Inhale as you lower down'],
    commonMistakes: ['Swinging the elbows forward to cheat the weight up', 'Using momentum from the hips', 'Not fully extending at the bottom', 'Letting the dumbbells swing outward'],
    safetyNotes: ['Keep the movement strict and controlled', 'Use lighter weight if you cannot maintain elbow position', 'Avoid leaning back as you curl'],
    referenceUrls: ['https://exrx.net/WeightExercises/Biceps/DBCurl'],
    isShared: true,
  },
  {
    name: 'Hammer Curl',
    category: 'upper-body',
    description: 'A biceps and brachialis curl with a neutral grip (palms facing each other). Builds the upper arm thickness and targets the brachialis muscle beneath the biceps.',
    setupCues: ['Stand with feet shoulder-width apart', 'Hold dumbbells at your sides with palms facing inward (neutral grip)', 'Keep your elbows close to your torso', 'Maintain a tall posture'],
    executionCues: ['Curl the dumbbells upward while keeping the palms facing each other', 'Squeeze at the top without rotating the wrist', 'Lower slowly to full extension', 'Keep both elbows stationary throughout'],
    breathingCues: ['Exhale as you curl up', 'Inhale as you lower down'],
    commonMistakes: ['Swinging the body to lift heavier weight', 'Letting the elbows drift forward', 'Using partial range of motion', 'Rotating the wrists during the curl'],
    safetyNotes: ['Keep the movement strict', 'The neutral grip is easier on the wrists than supinated curls', 'Use a controlled tempo on both phases'],
    referenceUrls: ['https://exrx.net/WeightExercises/Brachialis/DBHammerCurl'],
    isShared: true,
  },
  {
    name: 'Cable Triceps Pushdown',
    category: 'upper-body',
    description: 'An isolation exercise for the triceps using a cable machine. The continuous tension of the cable makes it effective for building triceps size and definition.',
    setupCues: ['Stand upright facing the cable machine', 'Grip the bar or rope attachment at chest height', 'Keep your elbows tucked tight against your sides', 'Plant your feet shoulder-width apart'],
    executionCues: ['Push the bar down until your arms are fully extended', 'Squeeze your triceps at the bottom', 'Return slowly to the starting position', 'Keep your elbows stationary — only the forearms should move'],
    breathingCues: ['Exhale as you push down', 'Inhale as the bar returns'],
    commonMistakes: ['Letting the elbows drift away from the body', 'Using body weight to push the bar down', 'Partial range of motion at the bottom', 'Not controlling the return phase'],
    safetyNotes: ['Keep your wrists neutral, not bent', 'Start with a moderate weight to learn the form', 'Avoid locking the elbows forcefully'],
    referenceUrls: ['https://exrx.net/WeightExercises/Triceps/CBTricepsExt'],
    isShared: true,
  },
  {
    name: 'Overhead Triceps Extension',
    category: 'upper-body',
    description: 'A triceps isolation exercise performed overhead, which targets the long head of the triceps — the largest of the three triceps heads. Can be done with a dumbbell, cable, or EZ bar.',
    setupCues: ['Sit or stand with your core braced', 'Hold a dumbbell or cable rope overhead with both hands', 'Keep your elbows close to your head, pointing forward', 'Upper arms should stay vertical throughout'],
    executionCues: ['Lower the weight behind your head by bending the elbows', 'Extend your arms back to the overhead position', 'Keep the movement slow and controlled', 'Squeeze the triceps at full extension'],
    breathingCues: ['Exhale as you extend upward', 'Inhale as you lower behind the head'],
    commonMistakes: ['Flaring the elbows outward', 'Moving the upper arms instead of keeping them fixed', 'Using too much weight and straining the shoulders', 'Not getting a full stretch at the bottom'],
    safetyNotes: ['Keep elbows close to the head to protect the shoulder joint', 'Start with light weight to ensure full range of motion', 'Avoid this exercise if you have shoulder mobility limitations'],
    referenceUrls: ['https://exrx.net/WeightExercises/Triceps/DBTricepsExt'],
    isShared: true,
  },
  {
    name: 'Close-Grip Bench Press',
    category: 'upper-body',
    description: 'A compound pressing exercise that shifts emphasis from the chest to the triceps by using a narrow grip on the barbell. Builds triceps strength and size while also working the chest and shoulders.',
    setupCues: ['Lie on a flat bench with feet planted', 'Grip the barbell with hands shoulder-width apart or slightly narrower', 'Keep your elbows close to your body', 'Retract your shoulder blades'],
    executionCues: ['Lower the bar to your lower chest over 2-3 seconds', 'Keep your elbows tucked, not flared', 'Press the bar back up to full extension', 'Maintain control throughout — no bouncing'],
    breathingCues: ['Inhale as you lower the bar', 'Exhale as you press it back up'],
    commonMistakes: ['Gripping too narrow (stresses the wrists)', 'Flaring the elbows outward (turns it into a chest press)', 'Bouncing the bar off the chest', 'Using the same weight as your regular bench press'],
    safetyNotes: ['Use a spotter for heavy sets', 'Keep wrists stacked over elbows', 'Start with 60-70% of your regular bench press weight'],
    referenceUrls: ['https://exrx.net/WeightExercises/Triceps/CloseGripBenchPress'],
    isShared: true,
  },
  {
    name: 'Barbell Back Squat',
    category: 'lower-body',
    description: 'The king of lower-body exercises. A compound movement that targets the quadriceps, glutes, hamstrings, and core. Builds overall leg strength and power.',
    setupCues: ['Set the bar on the upper traps (high bar) or rear delts (low bar)', 'Step back from the rack with feet shoulder-width apart', 'Point toes slightly outward', 'Brace your core and keep your chest up'],
    executionCues: ['Descend by bending at the hips and knees simultaneously', 'Go to at least parallel (thighs at or below knee height)', 'Keep your knees tracking over your toes', 'Drive through your heels to stand back up', 'Maintain a neutral spine throughout'],
    breathingCues: ['Inhale and brace before descending', 'Exhale as you drive up'],
    commonMistakes: ['Knees caving inward', 'Rounding the lower back (butt wink)', 'Rising onto the toes', 'Not reaching adequate depth', 'Letting the chest fall forward'],
    safetyNotes: ['Always use safety bars or a spotter', 'Start with an empty bar to warm up', 'Never round your back under load', 'Keep weight in your heels and mid-foot'],
    referenceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BBSquat'],
    isShared: true,
  },
  {
    name: 'Goblet Squat',
    category: 'lower-body',
    description: 'A beginner-friendly squat variation holding a single dumbbell or kettlebell at chest level. Excellent for learning squat mechanics before progressing to barbell squats.',
    setupCues: ['Hold a dumbbell or kettlebell vertically at chest level', 'Stand with feet slightly wider than shoulder width', 'Point toes slightly outward', 'Keep your chest tall and core braced'],
    executionCues: ['Descend into a squat, keeping the weight close to your chest', 'Go as deep as your mobility allows (aim for below parallel)', 'Keep your elbows inside your knees at the bottom', 'Drive through your heels to stand back up'],
    breathingCues: ['Inhale as you descend', 'Exhale as you stand up'],
    commonMistakes: ['Letting the weight pull you forward', 'Rising onto the toes', 'Knees caving inward', 'Not going deep enough'],
    safetyNotes: ['This is the safest squat to learn first', 'Keep the weight close to your body', 'Use a light weight until you can reach full depth comfortably'],
    referenceUrls: ['https://exrx.net/WeightExercises/Quadriceps/DBSquat'],
    isShared: true,
  },
  {
    name: 'Leg Press',
    category: 'lower-body',
    description: 'A machine-based squat alternative that targets the quadriceps, glutes, and hamstrings. The guided path makes it safe for heavy loading without spinal compression.',
    setupCues: ['Adjust the seat so your knees are bent at about 90 degrees at the bottom', 'Place your entire foot flat on the platform', 'Keep your feet at shoulder width or slightly wider', 'Do not lock the safety catches at full extension'],
    executionCues: ['Press the platform away by extending your legs', 'Stop just short of locking the knees at the top', 'Lower slowly over 2-3 seconds', 'Keep your lower back flat against the pad at all times'],
    breathingCues: ['Exhale as you press the platform away', 'Inhale as you lower it back'],
    commonMistakes: ['Lifting the heels off the platform', 'Locking the knees forcefully at the top', 'Lowering too deeply (causes lower back rounding)', 'Placing feet too high or too low on the platform'],
    safetyNotes: ['Always engage the safety catches when racking the weight', 'Start with light weight to learn the machine', 'Keep your back flat — never round it under load'],
    referenceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LVLegPress'],
    isShared: true,
  },
  {
    name: 'Walking Lunge',
    category: 'lower-body',
    description: 'A unilateral leg exercise that builds the quads, glutes, and hamstrings while improving balance and hip mobility. Can be done with bodyweight, dumbbells, or a barbell.',
    setupCues: ['Stand tall with feet hip-width apart', 'Hold dumbbells at your sides or rest a barbell on your upper back', 'Keep your chest up and core braced', 'Find a clear path of 10-15 meters'],
    executionCues: ['Take a large step forward', 'Lower your back knee toward the floor (do not touch)', 'Keep your front knee tracking over your toes (not beyond)', 'Push off the front foot and bring the back foot forward into the next step', 'Alternate legs with each step'],
    breathingCues: ['Inhale as you step and lower', 'Exhale as you push forward to the next step'],
    commonMistakes: ['Taking too short a step (overloads the front knee)', 'Letting the front knee cave inward', 'Leaning the torso forward excessively', 'Not controlling the descent'],
    safetyNotes: ['Start with bodyweight to learn the movement', 'Keep your core tight to stabilize', 'Avoid if you have acute knee pain — consult a professional'],
    referenceUrls: ['https://exrx.net/WeightExercises/Quadriceps/DBWalkingLunge'],
    isShared: true,
  },
  {
    name: 'Bulgarian Split Squat',
    category: 'lower-body',
    description: 'A challenging single-leg squat with the rear foot elevated. Builds quad and glute strength while addressing imbalances between legs. Requires balance and hip flexibility.',
    setupCues: ['Stand with a bench behind you', 'Place the top of your rear foot on the bench', 'Position your front foot far enough forward that your knee stays over your heel', 'Hold dumbbells at your sides or use bodyweight'],
    executionCues: ['Lower your body by bending the front knee', 'Descend until your front thigh is parallel to the floor', 'Keep your torso upright', 'Push through the front heel to return to standing', 'Keep the front knee tracking over the toes'],
    breathingCues: ['Inhale as you lower', 'Exhale as you push back up'],
    commonMistakes: ['Placing the front foot too close to the bench (strains the knee)', 'Leaning the torso forward excessively', 'Letting the front knee cave inward', 'Not lowering through a full range of motion'],
    safetyNotes: ['Start with bodyweight to find your ideal foot position', 'Use a wall or rack for balance if needed initially', 'Keep the movement slow and controlled'],
    referenceUrls: ['https://exrx.net/WeightExercises/Quadriceps/DBSplitSquat'],
    isShared: true,
  },
  {
    name: 'Romanian Deadlift',
    category: 'lower-body',
    description: 'A hip-hinge movement that targets the hamstrings, glutes, and lower back. Unlike a conventional deadlift, the knees stay mostly straight, emphasizing the posterior chain stretch.',
    setupCues: ['Hold a barbell or dumbbells at hip level with arms straight', 'Stand with feet hip-width apart', 'Keep a slight bend in the knees (do not lock them)', 'Brace your core and keep your chest up'],
    executionCues: ['Hinge at the hips, pushing your glutes backward', 'Lower the weight along your thighs toward the floor', 'Stop when you feel a deep hamstring stretch (usually mid-shin)', 'Drive your hips forward to return to standing', 'Keep the bar close to your body throughout'],
    breathingCues: ['Inhale as you hinge forward', 'Exhale as you drive the hips forward to stand'],
    commonMistakes: ['Rounding the back (major injury risk)', 'Bending the knees too much (turns it into a squat)', 'Letting the bar drift away from the body', 'Not achieving a full hamstring stretch'],
    safetyNotes: ['Keep your back flat and neutral at all times', 'Start with light weight to master the hip hinge', 'Stop if you feel lower back pain — check your form', 'Do not go lower than your mobility allows'],
    referenceUrls: ['https://exrx.net/WeightExercises/Hamstrings/BBRomanianDeadlift'],
    isShared: true,
  },
  {
    name: 'Lying Leg Curl',
    category: 'lower-body',
    description: 'An isolation exercise for the hamstrings using a lever curl machine. Performed lying face down, it targets the hamstring group through knee flexion.',
    setupCues: ['Lie prone on the bench with knees just past the edge', 'Place your lower legs under the lever pad', 'Grasp the handles for stability', 'Keep your hips flat against the bench'],
    executionCues: ['Curl the pad toward your glutes by flexing your knees', 'Squeeze the hamstrings at the top', 'Lower slowly with control', 'Keep your hips pinned to the bench — do not raise them'],
    breathingCues: ['Exhale as you curl up', 'Inhale as you lower down'],
    commonMistakes: ['Lifting the hips off the bench to cheat the weight', 'Using momentum to swing the pad', 'Not controlling the lowering phase', 'Partial range of motion at the top'],
    safetyNotes: ['Keep the movement slow and controlled', 'Start with light weight in the first month', 'Avoid jerking the weight up'],
    referenceUrls: ['https://exrx.net/WeightExercises/Hamstrings/LVLyingLegCurl'],
    isShared: true,
  },
  {
    name: 'Leg Extension',
    category: 'lower-body',
    description: 'An isolation exercise for the quadriceps using a lever extension machine. Straightens the knee against resistance, targeting the quadriceps group.',
    setupCues: ['Adjust the back pad so your knees align with the machine pivot', 'Place the front of your lower legs behind the pad', 'Sit back with your back against the pad', 'Grasp the handles for stability'],
    executionCues: ['Extend your legs until they are nearly straight', 'Squeeze the quads at the top for 1 second', 'Lower slowly over 2-3 seconds', 'Do not let the weight slam down at the bottom'],
    breathingCues: ['Exhale as you extend', 'Inhale as you lower back'],
    commonMistakes: ['Locking the knees forcefully at the top', 'Using too much weight', 'Partial range of motion', 'Letting the weight drop rapidly'],
    safetyNotes: ['Do not lock the knees aggressively', 'Control both directions of the movement', 'Avoid this exercise if you have current knee issues — consult a professional'],
    referenceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LVLegExtension'],
    isShared: true,
  },
  {
    name: 'Standing Calf Raise',
    category: 'lower-body',
    description: 'An isolation exercise for the gastrocnemius and soleus muscles of the calf. Can be done on a machine, with a barbell, or on a step with bodyweight.',
    setupCues: ['Place the balls of your feet on a platform or step', 'Keep your heels hanging off the edge', 'Stand tall with shoulders back', 'Hold a barbell or use the calf raise machine for resistance'],
    executionCues: ['Press up onto the balls of your feet as high as possible', 'Pause and squeeze at the top for 1 second', 'Lower slowly until you feel a stretch in the calves', 'Use a full range of motion — go all the way up and all the way down'],
    breathingCues: ['Exhale as you rise up', 'Inhale as you lower down'],
    commonMistakes: ['Bouncing at the bottom instead of pausing', 'Not reaching full extension at the top', 'Using momentum from the legs', 'Partial range of motion'],
    safetyNotes: ['Keep the movement controlled and deliberate', 'Start with moderate weight', 'Use a wall or rack for balance if doing bodyweight raises'],
    referenceUrls: ['https://exrx.net/WeightExercises/Gastrocnemius/BBCalfRaise'],
    isShared: true,
  },
  {
    name: 'Seated Calf Raise',
    category: 'lower-body',
    description: 'A calf isolation exercise performed seated, which targets the soleus muscle beneath the gastrocnemius. The bent-knee position de-emphasizes the gastroc and hits the soleus directly.',
    setupCues: ['Sit on the calf raise machine with the balls of your feet on the platform', 'Place the pad on your lower thighs just above the knee', 'Keep your toes pointed forward or slightly outward', 'Sit tall with your back against the pad'],
    executionCues: ['Press up onto the balls of your feet as high as possible', 'Pause and squeeze at the top', 'Lower slowly until you feel a deep stretch', 'Use a full range of motion on every rep'],
    breathingCues: ['Exhale as you press up', 'Inhale as you lower down'],
    commonMistakes: ['Bouncing at the bottom', 'Using momentum', 'Not achieving full plantar flexion at the top', 'Rushing the reps'],
    safetyNotes: ['Keep the movement slow and controlled', 'The seated position is gentler on the Achilles tendon', 'Start with moderate weight'],
    referenceUrls: ['https://exrx.net/WeightExercises/Soleus/LVSeatedCalfRaise'],
    isShared: true,
  },
  {
    name: 'Hip Thrust',
    category: 'lower-body',
    description: 'A glute-focused exercise performed by thrusting the hips upward against resistance. One of the most effective movements for building glute strength and size.',
    setupCues: ['Sit on the floor with your upper back against a bench', 'Roll a barbell into the crease of your hips (use a pad)', 'Plant your feet flat on the floor at hip width', 'Tuck your chin to your chest'],
    executionCues: ['Drive through your heels to lift your hips toward the ceiling', 'Squeeze your glutes hard at the top', 'Keep your core braced and ribs down', 'Lower under control to just below the starting position'],
    breathingCues: ['Exhale as you thrust up', 'Inhale as you lower down'],
    commonMistakes: ['Hyperextending the lower back at the top', 'Bouncing off the floor instead of pausing', 'Not squeezing the glutes at the peak', 'Letting the feet slide forward'],
    safetyNotes: ['Use a barbell pad to protect your hips', 'Keep your chin tucked — do not throw your head back', 'Stop the movement when your torso is parallel to the floor'],
    referenceUrls: ['https://exrx.net/WeightExercises/GluteusMaximus/BBHipThrust'],
    isShared: true,
  },
  {
    name: 'Hip Abduction Machine',
    category: 'lower-body',
    description: 'An isolation exercise for the gluteus medius and minimus (outer hips). Strengthens hip stability and helps correct knee valgus (caving inward) during squats and lunges.',
    setupCues: ['Sit upright on the abduction machine', 'Place the pads on the outside of your thighs or knees', 'Keep your back against the pad', 'Start with your legs together'],
    executionCues: ['Push your legs outward against the pads', 'Squeeze the outer glutes at the widest point', 'Return slowly to the starting position under control', 'Keep the movement smooth — no jerking'],
    breathingCues: ['Exhale as you push apart', 'Inhale as you return inward'],
    commonMistakes: ['Leaning forward to use momentum', 'Using too much weight', 'Not reaching full abduction', 'Rushing the return phase'],
    safetyNotes: ['Use a controlled tempo', 'Start with light resistance to feel the outer glutes working', 'Keep your torso stable throughout'],
    referenceUrls: ['https://exrx.net/WeightExercises/HipAbductors/LVHipAbduction'],
    isShared: true,
  },
  {
    name: 'Hip Adduction Machine',
    category: 'lower-body',
    description: 'An isolation exercise for the inner thigh muscles (adductors). Strengthens hip stability and complements abduction training for balanced hip function.',
    setupCues: ['Sit upright on the adduction machine', 'Place the pads on the inside of your thighs', 'Start with your legs spread apart to a comfortable position', 'Keep your back against the pad'],
    executionCues: ['Squeeze your legs together against the pads', 'Hold the contraction briefly at the midpoint', 'Return slowly to the starting position', 'Keep the movement controlled in both directions'],
    breathingCues: ['Exhale as you squeeze inward', 'Inhale as you let the legs spread apart'],
    commonMistakes: ['Arching the back', 'Using excessive momentum', 'Not achieving full adduction', 'Rushing the reps'],
    safetyNotes: ['Maintain an upright posture throughout', 'Start with light resistance', 'Avoid bouncing at the end range'],
    referenceUrls: ['https://exrx.net/WeightExercises/HipAdductors/LVHipAdduction'],
    isShared: true,
  },
  {
    name: 'Plank',
    category: 'core',
    description: 'An isometric core exercise that builds endurance in the abdominals, obliques, and lower back. The foundation of core stability training.',
    setupCues: ['Place your forearms on the floor with elbows under your shoulders', 'Extend your legs straight behind you', 'Keep your body in a straight line from head to heels', 'Brace your core as if expecting to be punched'],
    executionCues: ['Hold the position without letting your hips sag or rise', 'Keep your neck neutral — look at the floor', 'Breathe steadily — do not hold your breath', 'Squeeze your glutes and quads to maintain tension'],
    breathingCues: ['Breathe slowly and steadily throughout the hold', 'Do not hold your breath'],
    commonMistakes: ['Letting the hips sag toward the floor', 'Raising the hips too high (piking)', 'Holding the breath', 'Looking forward instead of down (strains the neck)'],
    safetyNotes: ['Start with 20-30 second holds and build up', 'Stop if you feel lower back pain — your form is breaking down', 'Quality over duration — a 20-second perfect plank beats a 60-second sloppy one'],
    referenceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/BWPlank'],
    isShared: true,
  },
  {
    name: 'Hanging Leg Raise',
    category: 'core',
    description: 'An advanced core exercise that targets the lower abdominals and hip flexors. Performed hanging from a pull-up bar, it also builds grip strength.',
    setupCues: ['Hang from a pull-up bar with an overhand grip', 'Keep your arms straight and shoulders engaged', 'Brace your core', 'Keep your legs straight for the full version (bend knees for easier)'],
    executionCues: ['Raise your legs until they are parallel to the floor (or higher)', 'Control the movement — do not swing', 'Lower your legs slowly to the starting position', 'Avoid using momentum to kick the legs up'],
    breathingCues: ['Exhale as you raise your legs', 'Inhale as you lower them'],
    commonMistakes: ['Swinging the body to generate momentum', 'Using the hip flexors instead of the abs', 'Dropping the legs quickly instead of lowering with control', 'Not engaging the core before starting the rep'],
    safetyNotes: ['Stop if you feel shoulder discomfort from the hang', 'Start with knee raises before progressing to straight leg', 'Use lifting straps if grip is the limiting factor'],
    referenceUrls: ['https://exrx.net/WeightExercises/HipFlexors/BWHangingLegRaise'],
    isShared: true,
  },
  {
    name: 'Cable Crunch',
    category: 'core',
    description: 'A weighted crunch using a cable machine that targets the rectus abdominis. Provides consistent resistance through the full range of motion.',
    setupCues: ['Kneel in front of a high cable pulley', 'Attach a rope handle', 'Hold the rope at the sides of your head', 'Keep your hips stationary throughout'],
    executionCues: ['Crunch your torso downward by flexing the abs', 'Bring your elbows toward your knees', 'Squeeze the abs at the bottom', 'Return slowly to the starting position under control'],
    breathingCues: ['Exhale as you crunch down', 'Inhale as you return up'],
    commonMistakes: ['Using the hips instead of the abs', 'Pulling with the arms', 'Not achieving full flexion', 'Going too fast and using momentum'],
    safetyNotes: ['Focus on the abdominal contraction, not the weight', 'Keep the movement at the torso, not the hips', 'Start with light weight to feel the abs working'],
    referenceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/CCKneelingCrunch'],
    isShared: true,
  },
  {
    name: 'Russian Twist',
    category: 'core',
    description: 'A rotational core exercise that targets the obliques and rectus abdominis. Can be done with bodyweight, a medicine ball, or a weight plate.',
    setupCues: ['Sit on the floor with your knees bent', 'Lean back slightly to engage your core', 'Hold a weight plate or medicine ball with both hands', 'Elevate your feet for more difficulty (optional)'],
    executionCues: ['Rotate your torso to one side, touching the weight to the floor', 'Rotate to the other side in a controlled motion', 'Keep your back straight and core engaged', 'Move from the torso, not the arms'],
    breathingCues: ['Exhale as you rotate to each side', 'Inhale as you pass through the center'],
    commonMistakes: ['Rounding the back', 'Using the arms instead of the obliques', 'Going too fast and losing control', 'Not achieving full rotation'],
    safetyNotes: ['Keep your spine long — do not round', 'Start with light weight or bodyweight', 'Avoid if you have lower back disc issues — consult a professional'],
    referenceUrls: ['https://exrx.net/WeightExercises/Obliques/BWRussianTwist'],
    isShared: true,
  },
  {
    name: 'Bird Dog',
    category: 'core',
    description: 'A core stabilization exercise that targets the deep stabilizers, glutes, and back extensors. Excellent for building anti-extension and anti-rotation control.',
    setupCues: ['Start on your hands and knees (quadruped position)', 'Hands under your shoulders, knees under your hips', 'Keep your spine neutral', 'Brace your core'],
    executionCues: ['Extend your right arm forward and your left leg backward simultaneously', 'Keep your hips level — do not let them tilt', 'Hold for 1-2 seconds at full extension', 'Return slowly and switch sides', 'Move slowly and deliberately with full control'],
    breathingCues: ['Exhale as you extend', 'Inhale as you return to the starting position'],
    commonMistakes: ['Letting the hips tilt or rotate', 'Rushing the movement', 'Not achieving full extension of arm and leg', 'Arching the lower back'],
    safetyNotes: ['This is a bodyweight stability exercise — no load needed', 'Keep the movement slow and controlled', 'Excellent for rehab and prehab'],
    referenceUrls: ['https://exrx.net/WeightExercises/BackGeneral/BWBirdDog'],
    isShared: true,
  },
  {
    name: 'Dead Bug',
    category: 'core',
    description: 'A core anti-extension exercise performed lying on the back. Trains the deep core stabilizers to maintain a neutral spine while moving the limbs. Ideal for beginners and rehab.',
    setupCues: ['Lie on your back with arms extended toward the ceiling', 'Bend your knees to 90 degrees (tabletop position)', 'Flatten your lower back against the floor', 'Brace your core'],
    executionCues: ['Slowly lower your right arm overhead and extend your left leg toward the floor', 'Keep your lower back pressed flat against the floor', 'Return to the starting position', 'Switch sides and repeat', 'Move slowly — this is a control exercise, not a speed drill'],
    breathingCues: ['Exhale as you extend the arm and leg', 'Inhale as you return to the starting position'],
    commonMistakes: ['Letting the lower back arch off the floor', 'Moving too fast', 'Not fully extending the limbs', 'Holding the breath'],
    safetyNotes: ['The key is keeping the back flat — if it arches, reduce the range', 'No weight needed for this exercise', 'Ideal for building fundamental core stability'],
    referenceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/BWDeadBug'],
    isShared: true,
  },
  {
    name: 'Mountain Climber',
    category: 'core',
    description: 'A dynamic core and cardio exercise that combines a plank position with alternating knee drives. Builds core stability, shoulder endurance, and cardiovascular fitness.',
    setupCues: ['Start in a high plank (push-up) position', 'Hands directly under your shoulders', 'Keep your body in a straight line', 'Brace your core'],
    executionCues: ['Drive one knee toward your chest', 'Return it quickly to the starting position', 'Alternate legs in a running motion', 'Keep your hips level — do not bounce up and down', 'Maintain the plank position throughout'],
    breathingCues: ['Breathe rapidly and steadily — do not hold your breath', 'Match your breathing to your leg pace'],
    commonMistakes: ['Bouncing the hips up and down', 'Letting the torso sag', 'Bringing the knees to the outside instead of straight forward', 'Going too fast and losing form'],
    safetyNotes: ['Start slow to maintain form, then increase speed', 'Keep your shoulders over your wrists', 'Stop if your shoulders fatigue before your core'],
    referenceUrls: ['https://exrx.net/Aerobic/MountainClimber'],
    isShared: true,
  },
  {
    name: 'Treadmill Walking',
    category: 'cardio',
    description: 'A low-impact cardiovascular exercise suitable for all fitness levels. Walking on a treadmill at moderate intensity improves heart health, burns calories, and aids recovery.',
    setupCues: ['Set the treadmill to a comfortable walking speed (3-5 km/h)', 'Start with a flat incline, then gradually increase if desired', 'Stand tall with shoulders back and core engaged', 'Look forward, not down at the console'],
    executionCues: ['Walk with a natural stride — land on your heel and roll through to the toe', 'Swing your arms naturally', 'Breathing should be elevated but you should be able to hold a conversation', 'For more intensity, increase incline rather than speed'],
    breathingCues: ['Breathe naturally and rhythmically', 'You should be breathing faster than at rest but not gasping'],
    commonMistakes: ['Holding onto the handrails continuously (reduces calorie burn and alters posture)', 'Looking down at the phone (strains the neck)', 'Taking overly long strides', 'Slouching while walking'],
    safetyNotes: ['Attach the safety clip to your clothing', 'Start slow and warm up for 5 minutes', 'If you feel dizzy or short of breath, slow down and step off carefully'],
    referenceUrls: ['https://exrx.net/Aerobic/WalkBriskTreadmill'],
    isShared: true,
  },
  {
    name: 'Stationary Cycling',
    category: 'cardio',
    description: 'A low-impact cardio exercise on a stationary bike. Ideal for building cardiovascular endurance without stress on the knees, hips, or ankles.',
    setupCues: ['Adjust the seat height so your knee has a slight bend at full extension', 'Adjust the handlebar so you can reach it without straining your back', 'Secure your feet in the pedals or straps', 'Set resistance to a moderate level'],
    executionCues: ['Pedal at a steady cadence of 60-90 rpm', 'Keep your core engaged and back relatively straight', 'Push down and pull up on the pedals for full engagement', 'Increase resistance for more intensity rather than just pedaling faster'],
    breathingCues: ['Breathe steadily and rhythmically', 'Match your breathing to your pedaling pace'],
    commonMistakes: ['Setting the seat too low (strains the knees)', 'Slouching over the handlebars', 'Using no resistance (pedaling too fast with no load)', 'Bouncing in the seat at high speeds'],
    safetyNotes: ['Start with 5 minutes at low resistance to warm up', 'Keep your knees tracking straight — do not let them bow outward or inward', 'If you have lower back pain, try a recumbent bike instead'],
    referenceUrls: ['https://exrx.net/Aerobic/CyclingStationaryL'],
    isShared: true,
  },
  {
    name: 'Rowing Machine',
    category: 'cardio',
    description: 'A full-body cardiovascular exercise on an ergometer (rowing machine). Engages legs, back, core, and arms in a single coordinated movement. One of the most efficient cardio options.',
    setupCues: ['Adjust the foot straps so your feet are secure', 'Set the damper (resistance) to 4-6 for general fitness', 'Sit with your shins vertical and back straight', 'Grip the handle with both hands'],
    executionCues: ['Drive through your legs first, then pivot the back, then pull with the arms', 'Keep your back straight — do not round', 'Pull the handle to your lower ribs', 'Reverse the sequence to return: arms out, then lean forward, then bend knees', 'Keep the chain flat — do not let it jerk or bounce'],
    breathingCues: ['Exhale during the drive (the pull)', 'Inhale during the recovery (the return)'],
    commonMistakes: ['Pulling with the arms before the legs have driven', 'Rounding the back during the pull', 'Rushing the recovery phase', 'Leaning too far back at the end of the stroke'],
    safetyNotes: ['Learn the sequence: legs, back, arms — then reverse', 'Start with low resistance to master the technique', 'Keep your core braced to protect your lower back'],
    referenceUrls: ['https://exrx.net/Aerobic/RowingStationary'],
    isShared: true,
  },
  {
    name: 'Jump Rope',
    category: 'cardio',
    description: 'A high-intensity cardio exercise that builds coordination, calf endurance, and cardiovascular fitness. Burns more calories per minute than most cardio options.',
    setupCues: ['Choose a rope that reaches your armpits when stood on at the midpoint', 'Hold the handles lightly — do not grip tightly', 'Keep your elbows close to your sides', 'Stand on the balls of your feet'],
    executionCues: ['Swing the rope with your wrists, not your arms', 'Jump just 1-2 inches off the floor — small hops', 'Land softly on the balls of your feet', 'Keep a steady rhythm', 'Look forward, not down at your feet'],
    breathingCues: ['Breathe steadily and rhythmically', 'Do not hold your breath during sets'],
    commonMistakes: ['Jumping too high (wastes energy)', 'Swinging the arms instead of the wrists', 'Looking down at the feet (strains the neck)', 'Gripping the handles too tightly'],
    safetyNotes: ['Start with 30-second intervals and build up', 'Wear cushioned shoes to protect the ankles and knees', 'Avoid jumping on hard concrete — use a mat or wooden floor'],
    referenceUrls: ['https://exrx.net/Aerobic/JumpRope'],
    isShared: true,
  },
  {
    name: 'Stair Climber',
    category: 'cardio',
    description: 'A cardio and leg-strengthening exercise on a stair-climbing machine. Combines cardiovascular training with quadriceps and glute engagement.',
    setupCues: ['Step onto the machine and set a moderate climbing speed', 'Keep your entire foot on each step', 'Stand tall with your core engaged', 'Start at a slow speed to warm up'],
    executionCues: ['Climb with a steady, controlled pace', 'Keep your posture upright — do not lean on the handrails', 'Use your legs to drive each step, not your arms', 'Keep your knees tracking over your toes'],
    breathingCues: ['Breathe steadily and rhythmically', 'You should be breathing faster than walking but able to speak short sentences'],
    commonMistakes: ['Leaning heavily on the handrails (removes the leg workload)', 'Taking tiny steps', 'Looking down at the feet continuously', 'Going too fast and losing control'],
    safetyNotes: ['Use the handrails only for balance, not support', 'Start with 5 minutes at a slow pace', 'Stop if you feel knee discomfort — reduce the speed'],
    referenceUrls: ['https://exrx.net/Aerobic/StairClimber'],
    isShared: true,
  },
  {
    name: 'Brisk Walking',
    category: 'cardio',
    description: 'Outdoor or indoor walking at a pace that elevates your heart rate. The most accessible form of cardio — requires no equipment and is ideal for active recovery days.',
    setupCues: ['Wear comfortable, supportive shoes', 'Start at your normal walking pace for 5 minutes', 'Gradually increase to a brisk pace', 'Keep your shoulders relaxed and arms swinging naturally'],
    executionCues: ['Walk at a pace that makes you breathe faster but still allows conversation', 'Land heel-first, roll through to the toe', 'Take natural-length strides — do not overstride', 'Swing your arms to increase calorie burn'],
    breathingCues: ['Breathe naturally and rhythmically', 'You should be able to talk but not sing'],
    commonMistakes: ['Overstriding (strains the hamstrings and reduces efficiency)', 'Looking down at the phone', 'Slouching the shoulders', 'Walking too slowly to elevate heart rate'],
    safetyNotes: ['Walk in well-lit, safe areas', 'Hydrate before and after, especially in heat', 'If walking outdoors, be aware of traffic and terrain'],
    referenceUrls: ['https://exrx.net/Aerobic/WalkBrisk'],
    isShared: true,
  },
  {
    name: 'Back Extension',
    category: 'core',
    description: 'A lower back and posterior chain exercise performed on a back extension bench or Roman chair. Strengthens the erector spinae, glutes, and hamstrings.',
    setupCues: ['Position the pad so your hips are at the top edge', 'Place your feet against the platform with ankles secured', 'Cross your arms in front of your chest or place hands behind your head', 'Keep your spine neutral at the starting position'],
    executionCues: ['Lower your torso toward the floor by hinging at the hips', 'Stop when you feel a stretch in your hamstrings', 'Raise your torso back to neutral by contracting your lower back and glutes', 'Do not hyperextend beyond the neutral spine position'],
    breathingCues: ['Inhale as you lower your torso', 'Exhale as you raise back to neutral'],
    commonMistakes: ['Hyperextending the back at the top (injury risk)', 'Using momentum and bouncing', 'Rounding the back during the movement', 'Going too fast'],
    safetyNotes: ['Only perform if you are comfortable with the setup', 'Stop immediately if you feel sharp lower back pain', 'Start with bodyweight only — add resistance gradually'],
    referenceUrls: ['https://exrx.net/WeightExercises/ErectorSpinae/LVBackExtension'],
    isShared: true,
  },
];

export default defaultExercises;
